import { AUTORUN, BODY, CHECKER, CLICKED, CONDITION, CONNECTED, DISPLAY, GETDATA, HOSTINGCHECKER, PASSDATA, REDUX } from "./Library/Connection.js";

window.BODY=BODY;
window.CONDITION=CONDITION;
window.DISPLAY=DISPLAY;
window.CONNECTED=CONNECTED;
window.PASSDATA=PASSDATA;
window.CHECKER=CHECKER;
window.CLICKED=CLICKED;
window.REDUX=REDUX;
window.GETDATA=GETDATA;
window.HOSTINGCHECKER=HOSTINGCHECKER;
window.AUTORUN=AUTORUN();