export const CLOUDSTART=()=>{

const START=`AUTORUN();BODIED();INSPECTION();URLCOLLECTOR();ZOOM();HOSTINGUPDATER();OPERATINGSYSTEM();UGANDANDISTRICITS();MONTHS();COUNTRIES();INSTALLER();COLORS();CURRENCIES();PROJECTSYNC();ONLINECHECKER();WEBKIT();DOMAINNAMECHANGE();
`;

localStorage.setItem('RUN',START);

};